/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef XBOXGAMEPAD_AUTODEFS_H
#define XBOXGAMEPAD_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_XBOXGAMEPAD_NAME "XBoxGamePad"
#define S3E_EXT_XBOXGAMEPAD_HASH 0x1e9ba715

#endif /* !XBOXGAMEPAD_AUTODEFS_H */
