/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "XBoxGamePad_autodefs.h"
#include "s3eEdk.h"
#include "XBoxGamePad.h"
//Declarations of Init and Term functions
extern s3eResult XBoxGamePadInit();
extern void XBoxGamePadTerminate();


void XBoxGamePadRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[22];
    funcPtrs[0] = (void*)XBoxPadInit;
    funcPtrs[1] = (void*)XBoxPadUpdate;
    funcPtrs[2] = (void*)XBoxPadIsConnected;
    funcPtrs[3] = (void*)XBoxPadVibrate;
    funcPtrs[4] = (void*)XBoxPadXAxisL;
    funcPtrs[5] = (void*)XBoxPadYAxisL;
    funcPtrs[6] = (void*)XBoxPadXAxisR;
    funcPtrs[7] = (void*)XBoxPadYAxisR;
    funcPtrs[8] = (void*)XBoxPadXDPad;
    funcPtrs[9] = (void*)XBoxPadYDPad;
    funcPtrs[10] = (void*)XBoxPadLeftThumb;
    funcPtrs[11] = (void*)XBoxPadRightThumb;
    funcPtrs[12] = (void*)XBoxPadAButton;
    funcPtrs[13] = (void*)XBoxPadBButton;
    funcPtrs[14] = (void*)XBoxPadXButton;
    funcPtrs[15] = (void*)XBoxPadYButton;
    funcPtrs[16] = (void*)XBoxPadLeftShoulder;
    funcPtrs[17] = (void*)XBoxPadRightShoulder;
    funcPtrs[18] = (void*)XBoxPadStartButton;
    funcPtrs[19] = (void*)XBoxPadBackButton;
    funcPtrs[20] = (void*)XBoxPadLeftTrigger;
    funcPtrs[21] = (void*)XBoxPadRightTrigger;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[22] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("XBoxGamePad", funcPtrs, sizeof(funcPtrs), flags, XBoxGamePadInit, XBoxGamePadTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int XBoxGamePadStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&XBoxGamePadRegisterExt;
    return 0;
}

int g_XBoxGamePadVal = XBoxGamePadStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    XBoxGamePadRegisterExt();
}
#endif

#endif
