/*
 * Copyright (C) 2001-2012 Ideaworks3D Ltd.
 * All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Ideaworks Labs.
 * This file consists of source code released by Ideaworks Labs under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_XBOXGAMEPAD_H
#define S3E_EXT_XBOXGAMEPAD_H

#include <s3eTypes.h>
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the XBoxGamePad extension is available.
 */
s3eBool XBoxGamePadAvailable();

s3eResult XBoxPadInit();

s3eResult XBoxPadUpdate();

bool XBoxPadIsConnected(int controller);

bool XBoxPadVibrate(int controller,int leftVal, int rightVal);

double XBoxPadXAxisL(int controller);

double XBoxPadYAxisL(int controller);

double XBoxPadXAxisR(int controller);

double XBoxPadYAxisR(int controller);

double XBoxPadXDPad(int controller);

double XBoxPadYDPad(int controller);

bool XBoxPadLeftThumb(int controller);

bool XBoxPadRightThumb(int controller);

bool XBoxPadAButton(int controller);

bool XBoxPadBButton(int controller);

bool XBoxPadXButton(int controller);

bool XBoxPadYButton(int controller);

bool XBoxPadLeftShoulder(int controller);

bool XBoxPadRightShoulder(int controller);

bool XBoxPadStartButton(int controller);

bool XBoxPadBackButton(int controller);

double XBoxPadLeftTrigger(int controller);

double XBoxPadRightTrigger(int controller);

S3E_END_C_DECL

#endif /* !S3E_EXT_XBOXGAMEPAD_H */
